name: 'Sign Android release'
description: 'An action to sign an Android release APK or AAB'
author: 'r0adkll'
branding:
  icon: 'edit'
  color: 'orange'
inputs:
  releaseDirectory:
    description: 'The directory to find your release to sign'
    required: true
  signingKeyBase64:
    description: 'The key used to sign your release in base64 encoded format'
    required: true
  alias:
    description: 'The key alias'
    required: true
  keyStorePassword:
    description: 'The password to the keystore'
    required: true
  keyPassword:
    description: 'The password for the key'
    required: false
outputs:
  signedReleaseFile:
    description: 'The signed release APK or AAB file'
runs:
  using: 'node12'
  main: 'lib/main.js'
